[project]
name = "kpground-api"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Scott Prelewicz", email = "sprelewicz@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.1",
    "django-cors-headers>=4.9.0",
    "django-oauth-toolkit>=3.4.0",
    "djangorestframework>=3.18.0",
    "gunicorn>=26.2.0",
    "psycopg[binary]>=3.3.4",
    "python-decouple>=3.8",
    "whitenoise>=6.12.0",
]

[tool.uv]
package = false
