# Generated by Django 6.1 on 2026-08-20 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(choices=[('cat', 'Cat'), ('mouse', 'Mouse'), ('dog', 'Dog')], max_length=10)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('cosmetic', 'Cosmetic'), ('perk', 'Perk')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField()),
                ('min_level', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('character', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CharacterWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(choices=[('cat', 'Cat'), ('mouse', 'Mouse'), ('dog', 'Dog')], max_length=10)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'character')},
            },
        ),
        migrations.CreateModel(
            name='DailyGiftClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_date', models.DateField()),
                ('coins_awarded_per_character', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_gift_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'claimed_date')},
            },
        ),
        migrations.CreateModel(
            name='OwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kattrap.storeitem')),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
