# Generated by Django 6.1 on 2026-08-21 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kattrap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='slot',
            field=models.CharField(blank=True, choices=[('outfit', 'Outfit')], max_length=20),
        ),
        migrations.CreateModel(
            name='EquippedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(choices=[('cat', 'Cat'), ('mouse', 'Mouse'), ('dog', 'Dog')], max_length=10)),
                ('slot', models.CharField(choices=[('outfit', 'Outfit')], max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kattrap.storeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'character', 'slot')},
            },
        ),
    ]
