# Generated by Django 6.1 on 2026-08-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kattrap', '0002_storeitem_slot_equippeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='sprite_src',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
