# Generated by Django 6.1 on 2026-09-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kattrap', '0003_storeitem_sprite_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='character',
            field=models.CharField(blank=True, choices=[('cat', 'Cat'), ('mouse', 'Mouse'), ('dog', 'Dog')], max_length=10),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='item_type',
            field=models.CharField(choices=[('cosmetic', 'Cosmetic'), ('perk', 'Perk'), ('decor', 'Decor')], max_length=10),
        ),
    ]
