"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
# No hardcoded fallback for SECRET_KEY - a real one must come from the
# environment in any deployed environment. Local dev uses .env (see .env.example).
SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Render sets this automatically on every deploy to the service's own
# *.onrender.com hostname - append it so ALLOWED_HOSTS doesn't need to be
# hand-updated with a value that isn't known until the service is created.
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default='')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Render terminates TLS at the edge and forwards to gunicorn over plain
# HTTP, so Django has to be told explicitly which header carries the
# original scheme - without this, request.is_secure() can't be trusted and
# CSRF's Origin check (which compares the browser's Origin header against
# request.scheme + get_host()) fails with "CSRF verification failed" on
# every POST (e.g. logging into /admin/), even with a correct password.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Must list the actual origin(s) users load this API's own pages (e.g.
# /admin/) from, scheme included - distinct from CORS_ALLOWED_ORIGINS below,
# which is about other origins' JS calling this API, not this API's own forms.
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'oauth2_provider',
    'accounts',
    'kattrap',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The frontends (kattrap, kpground, future games) are separate static sites,
# not served by this API - CORS has to be opened explicitly per origin.
# Token auth (see REST_FRAMEWORK below) doesn't rely on cookies, but CORS
# still gates which origins may call the API from a browser at all.
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    # 8080, not 8000 - this API's own dev server already runs on 8000
    # (manage.py runserver's default). Local KatTrap dev should be served
    # on 8080 (e.g. `python3 -m http.server 8080`) to avoid the collision.
    default='http://localhost:8080,http://127.0.0.1:8080',
    cast=Csv(),
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Password grant only (no redirect/consent flow) - both frontends are
# first-party static sites with no server to handle an OAuth2 redirect
# callback, so the "Login" button POSTs username/password straight to
# /o/token/. Access tokens are deliberately long-lived (14 days) so the
# vanilla-JS frontend doesn't need refresh-token handling built yet -
# revisit if that tradeoff stops feeling acceptable.
OAUTH2_PROVIDER = {
    'SCOPES': {'read': 'Read access', 'write': 'Write access'},
    'ACCESS_TOKEN_EXPIRE_SECONDS': 60 * 60 * 24 * 14,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 60 * 60 * 24 * 60,
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# DATABASE_URL points at Neon in any real environment (see .env.example).
# Falls back to local SQLite so `manage.py runserver` works with zero setup.

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# Served directly by whitenoise (no separate static-file host needed) -
# just admin/DRF-browsable-API assets, this API has no other static content.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# kpground-api project settings

# Temporary, easy-to-disable no-password login for a single known account
# (Kathryn) - see accounts app. Flip off once a real login flow exists for
# anyone else, or if this ever stops being just for her.
ENABLE_KATHRYN_QUICKLOGIN = config('ENABLE_KATHRYN_QUICKLOGIN', default=True, cast=bool)
